version: '3'
services:
  react:
    build: ./docker-React/test-page
    ports:
      - "3000:3000"
    volumes:
      - ./docker-React/test-page/app
    container_name: react
    restart: unless-stopped
    stdin_open: true  # Habilitar entrada interactiva
    tty: true         # Habilitar tty
    command: /bin/bash  # Cambiar el comando para iniciar una shell interactiva
