version: '3'
services:
  react:
    build: ./dockerReact/jsPage
    ports:
      - "3000:3000"
    volumes:
      - ./dockerReact/jsPage:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
    container_name: react
    restart: unless-stopped
    stdin_open: true  # Habilitar entrada interactiva
    tty: true         # Habilitar tty
    command: npm start

  react-ts:
    build: ./dockerReact/tsPage
    ports:
      - "3001:3000"
    volumes:
      - ./dockerReact/tsPage:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
    container_name: react-ts
    restart: unless-stopped
    stdin_open: true  # Habilitar entrada interactiva
    tty: true         # Habilitar tty
    command: npm start
